name: Build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean Cache
        working-directory: ./mypfinance-frontend
        run: |
          npm cache clean --force
      - name: CI Install
        working-directory: ./mypfinance-frontend
        run: |
          npm ci
      - name: NPM Install
        working-directory: ./mypfinance-frontend
        run: |
          npm install
      - name: Production Build
        working-directory: ./mypfinance-frontend
        run: |
          npm run build
        env:
          CI: false